name: Node.js CI

on: [pull_request, push]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.16.3
      uses: actions/setup-node@v2
      with:
        node-version: 12.16.3 #change to proper npm version
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.16.3
      uses: actions/setup-node@v2
      with:
        node-version: 12.16.3 #change to proper npm version
        cache: 'npm'
    - run: npm ci
   # - run: # change to whatever command is used to run unit